const fs = require('fs');
const path = require('path');
const cfgPath = path.resolve(__dirname, 'tailwind-custom.json');
let custom = {
    colors: {
        primary: '#1F5D2B',
        secondary: '#A2B917'
    }
};
try {
    custom = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
} catch (e) {
}
// Backwards compatibility: if legacy `color` array form is used, normalize it into colors object
if (!custom.colors && Array.isArray(custom.color)) {
    custom.colors = Object.assign({}, ...custom.color);
}
const darkMode = custom.darkMode ? 'class' : 'media';
module.exports = {
    darkMode,
    content: [
        '../../themes/**/*.php',
        '../../themes/**/*.twig',
        '../../themes/**/*.js',
        '../../themes/**/*.jsx',
        '../../themes/**/*.ts',
        '../../themes/**/*.tsx',
        '../../themes/**/*.vue',
        '../../themes/**/*.html',
        './src/**/*.{js,ts,jsx,tsx,php,html}'
    ],
    safelist: [
        // Layout and display
        'block',
        'flex',
        'inline-flex',
        'grid',
        'inline-grid',
        'items-center',
        'items-end',
        'justify-center',
        'justify-between',
        'justify-start',
        'justify-end',
        'flex-wrap',
        'flex-col',
        'md:flex-col',
        'shrink-0',
        'col-span-2',
        'md:col-span-1',
        'grid-cols-3',
        'md:grid-cols-5',
        'gap-3',
        'md:gap-5',
        'gap-5',
        'gap-6',
        'place-items-center',
        'content-center',
        'md:justify-start',
        // Sizing
        'w-[9rem]',
        'h-[6rem]',
        'md:w-[12rem]',
        'md:h-[9rem]',
        'lg:w-[15rem]',
        'lg:h-[12rem]',
        'w-[14rem]',
        'h-[12rem]',
        'md:w-[22rem]',
        'md:h-[16rem]',
        'w-[600px]',
        'max-w-[1200px]',
        'w-full',
        'h-full',
        'min-h-screen',
        // Spacing
        'p-3',
        'p-6',
        'p-10',
        'px-5',
        'py-6',
        'pr-4',
        'md:py-2',
        'pt-5',
        'mt-3',
        'sm:mt-0',
        'mb-1',
        '!m-0',
        'mx-auto',
        'my-5',
        'px-4',
        'py-3',
        // Colors and Backgrounds
        'bg-[#1f5d2b]',
        'bg-red-500',
        'bg-gradient-to-r',
        'bg-gradient-to-l',
        'bg-gradient-to-t',
        'bg-gradient-to-b',
        'bg-gradient-to-tr',
        'bg-gradient-to-bl',
        'from-[#1f5d2b]',
        'to-[#a2b917]',
        'from-[#a2b917]',
        'to-[#1f5d2b]',
        'hover:border-[#1f5d2b]',
        'border-[#a2b917]',
        'text-red-500',
        'text-gray-500',
        '!text-white',
        'opacity-50',
        'backdrop-blur-sm',
        'hover:bg-[#a2b917]',
        'hover:text-[#1f5d2b]',
        // Typography
        'text-[0.7rem]',
        'text-sm',
        'text-base',
        'md:text-base',
        'md:text-lg',
        'lg:text-xl',
        'md:text-2xl',
        'sm:text-xl',
        'sm:text-2xl',
        'lg:text-3xl',
        '!text-sm',
        '!leading-none',
        '!leading-tight',
        'md:!leading-6',
        'leading-[0.9rem]',
        'font-thin',
        'font-semibold',
        'font-bold',
        'md:font-extrabold',
        '!font-spartan',
        '!font-dancing',
        '!font-lato',
        '!font-montserrat',
        '!font-sans',
        '!whitespace-nowrap',
        'tracking-tight',
        'tracking-wide',
        'uppercase',
        'lowercase',
        'italic',
        // Borders & Rounding
        'border',
        'border-[#a2b917]',
        'hover:border-[#1f5d2b]',
        'rounded-sm',
        'rounded-md',
        'rounded-t',
        'sm:rounded-l',
        'rounded-lg',
        'rounded-2xl',
        'shadow',
        'shadow-md',
        'shadow-lg',
        'shadow-[#1f5d2b]/40',
        'no-underline',
        // Transforms & Transitions
        'scale-75',
        'md:scale-100',
        'hover:scale-105',
        'transition',
        'duration-200',
        'duration-300',
        'ease-in-out',
        'transform',
        'hover:rotate-1',
        // Special & Utility
        'z-[999]',
        'cursor-pointer',
        'select-none',
        'overflow-hidden',
        'overflow-x-auto',
        'overflow-y-scroll',
        'object-cover',
        'object-center',
        'text-center',
        'text-left',
        'text-right',
        'shadow-inner',
        // Arbitrary Variants & Child Styling
        '[&>li]:flex',
        '[&>li]:flex-wrap',
        '[&>li]:whitespace-nowrap',
        '[&>li>span]:mr-1',
        '[&>li>a]:!text-white',
        '[&>li>a:hover]:!text-[#a2b917]',
        '[&>p]:text-gray-600',
        '[&>img]:rounded-lg',
        // Pattern for Gradient Detection
        { pattern: /bg-gradient-to-(r|l|t|b|tr|tl|br|bl)/ },
    ],
    theme: {
        extend: {
            colors: custom.colors || {},
            fontFamily: {
                dancing: ['"Dancing Script"', 'cursive'],
                lato: ['Lato', 'sans-serif'],
                spartan: ['"League Spartan"', 'sans-serif'],
                montserrat: ['Montserrat', 'sans-serif'],
                sans: custom.fontFamily ? custom.fontFamily.split(',').map(s => s.trim()) : ['Inter', 'system-ui', 'sans-serif']
            }
        }
    },
    plugins: []
};
