const fs = require('fs');
const path = require('path');
const cfgPath = path.resolve(__dirname, 'tailwind-custom.json');
let custom = {
    colors: {
        primary: '#1F5D2B',
        secondary: '#A2B917'
    }
};
try {
    custom = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
} catch (e) {
}
// Backwards compatibility: if legacy `color` array form is used, normalize it into colors object
if (!custom.colors && Array.isArray(custom.color)) {
    custom.colors = Object.assign({}, ...custom.color);
}
const extendedColors = Object.assign({}, custom.colors || {}, {
    'cbc-yellow-green': (custom.colors && (custom.colors['cbc-yellow-green'] || custom.colors.secondary)) || '#A2B917',
});
const darkMode = custom.darkMode ? 'class' : 'media';
module.exports = {
    darkMode,
    content: [
        '../../themes/**/*.php',
        '../../themes/**/*.twig',
        '../../themes/**/*.js',
        '../../themes/**/*.jsx',
        '../../themes/**/*.ts',
        '../../themes/**/*.tsx',
        '../../themes/**/*.vue',
        '../../themes/**/*.html',
        '../../plugins/**/*.php',
        './src/**/*.{js,ts,jsx,tsx,php,html}',
        '../../wp-admin/**/*.php',
        '../../wp-includes/**/*.php'
    ],
    safelist: [
        // Added for walker hover persistence
        'group',
        'group-hover:flex',
        'hidden',
        'top-full',
        'left-0',
        'pt-2',
        'mb-2',
        // Layout and display
        'relative',
        'flex',
        'items-center',
        'hover:bg-cbc-yellow-green',
        'duration-400',
        'ease-in-out',
        'absolute',
        'flex',
        'flex-col',
        'bg-gray-100',
        'z-[46]',
        'shadow-md',
        'p-3',
        'text-subtitle',
        'mt-2',
        'shadow-md',
        'p-2',
        'z-[100]',
        'px-3',
        'py-1',
        'text-gray-100',
        'group-hover:flex',
        'whitespace-nowrap',
        'text-normal',
        'inline-flex',
        'items-center',
        'px-1',
        'pt-1',
        'border-b-2',
        'border-transparent',
        'text-sm',
        'font-medium',
        'leading-5',
        'hover:border-gray-300',
        'focus:outline-none',
        'focus:text-gray-700',
        'focus:border-gray-300',
        'transition',
        'duration-150',
        'ease-in-out',
        'ml-2',
        '-mr-0.5',
        'h-4',
        'w-4',
        'flex',
        'text-gray-100',
        'items-center',
        'hover:bg-cbc-yellow-green',
        'duration-400',
        'ease-in-out',
        'text-gray-700',
        'px-3',
        'py-1',
        'whitespace-nowrap',
        'text-normal',
        'inline-flex',
        'items-center',
        'px-1',
        'pt-1',
        'border-b-2',
        'border-transparent',
        'text-sm',
        'font-medium',
        'leading-5',
        'hover:border-gray-300',
        'focus:outline-none',
        'focus:text-gray-700',
        'focus:border-gray-300',
        'transition',
        'duration-150',
        'ease-in-out',
        'fixed',
        'w-full',
        'h-full',
        'top-0',
        'left-0',
        'z-[1]',
        'block',
        'sm:block',
        'sm:hidden',
        'flex',
        'p-8',
        'py-2.5',
        'px-4',
        'hover:bg-[#a2b917]',
        'inline-flex',
        'grid',
        'inline-grid',
        'items-center',
        'items-end',
        'justify-center',
        'justify-between',
        'justify-start',
        'justify-end',
        'flex-wrap',
        'flex-col',
        'md:flex-col',
        'shrink-0',
        'col-span-2',
        'sm:gap-2',
        'flex-col',
        'sm:flex-row',
        'md:col-span-1',
        'grid-cols-3',
        'md:grid-cols-5',
        'gap-3',
        'md:gap-5',
        'gap-5',
        'gap-6',
        'bg-opacity-50',
        '!text-white',
        'list-none',
        'place-items-center',
        'content-center',
        'bg-gradient-to-r',
        'text-wrap',
        'from-[#1f5d2b]',
        'to-[#a2b917]',
        'items-start',
        'sm:items-center',
        'md:justify-start',
        // Sizing
        'w-[9rem]',
        'overflow-x-auto',
        'h-[6rem]',
        'md:w-[12rem]',
        'md:h-[9rem]',
        'lg:w-[15rem]',
        'lg:h-[12rem]',
        'h-[100vh]',
        'w-32',
        'space-y-6',
        'w-48',
        'md:w-48',
        'h-48',
        'h-64',
        'md:h-64',
        'w-[14rem]',
        'h-[12rem]',
        'md:w-[22rem]',
        'md:h-[16rem]',
        'w-[600px]',
        'max-w-[1200px]',
        'w-full',
        'h-full',
        'min-h-screen',
        'justify-items-center',
        'min-h-[2.5em]',
        'max-h-[2.5em]',
        'text-[9px]',
        'whitespace-pre-wrap',
        'whitespace-break-spaces',
        'whitespace-normal',
        // Spacing
        'line-clamp-2',
        'md:line-clamp-3',
        'space-y-10',
        'p-3',
        'p-6',
        'p-10',
        'pl-6',
        'pr-6',
        'mx-2',
        'px-5',
        'py-6',
        'md:text-sm',
        'md:text-base',
        'md:pr-4',
        'pr-4',
        'wrap',
        'p-4',
        'max-w-4xl',
        'mx-auto',
        'space-y-6',
        'space-y-4',
        'flex',
        'items-center',
        'space-x-2',
        'flex-grow',
        'text-3xl',
        'font-bold',
        'mb-4',
        'mb-6',
        'block',
        'text-sm',
        'font-medium',
        'text-gray-700',
        'text-red-500',
        'mt-2',
        'text-gray-500',
        'text-indigo-600',
        'text-lg',
        'text-gray-900',
        'text-base',
        'text-white',
        'text-xs',
        'text-green-600',
        'hover:text-green-900',
        'text-yellow-600',
        'hover:text-yellow-900',
        'text-red-600',
        'hover:text-red-900',
        'text-gray-300',
        'text-center',
        'text-ellipsis',
        'mt-1',
        'w-full',
        'border',
        'border-gray-300',
        'rounded-md',
        'shadow-sm',
        'p-2',
        'focus:ring-indigo-500',
        'focus:border-indigo-500',
        'inline-flex',
        'justify-center',
        'py-3',
        'px-6',
        'border-transparent',
        'bg-indigo-600',
        'hover:bg-indigo-700',
        'focus:outline-none',
        'focus:ring-2',
        'focus:ring-offset-2',
        'focus:ring-indigo-500',
        'px-3',
        'py-2',
        'bg-white',
        'hover:bg-gray-50',
        'text-gray-700',
        'text-sm',
        'ml-2',
        'w-fit',
        'w-[50%]',
        'w-[25%]',
        'md:w-20',
        'w-10',
        'shadow',
        'overflow-hidden',
        'border-b',
        'border-gray-200',
        'sm:rounded-lg',
        'min-w-full',
        'divide-y',
        'divide-gray-200',
        'bg-gray-50',
        'px-6',
        'py-3',
        'text-left',
        'uppercase',
        'tracking-wider',
        'whitespace-nowrap',
        'font-medium',
        'bg-white',
        'max-w-lg',
        'object-contain',
        'w-16',
        'h-16',
        'p-4',
        'bg-yellow-100',
        'border',
        'border-yellow-400',
        'text-yellow-700',
        'rounded-md',
        'bg-blue-100',
        'border-blue-400',
        'text-blue-700',
        'mb-4',
        'p-3',
        'bg-gray-100',
        'p-1',
        'rounded',
        'border-t',
        'pt-6',
        'inline-block',
        'pr-2',
        'md:py-2',
        'pt-5',
        'mt-3',
        'sm:mt-0',
        'mb-1',
        '!m-0',
        'mx-auto',
        'my-5',
        'px-4',
        'px-2',
        'w-34',
        'py-3',
        'bg-gradient-to-r',
        'to-white/90',
        'via-white/70',
        'group-hover:[text-shadow:1px_1px_0_white,-1px_1px_0_white,1px_-1px_0_white,-1px_-1px_0_white,0_2px_0_white,2px_0_0_white,-2px_0_0_white,0_-2px_0_white]',
        'from-transparent',
        // Colors and Backgrounds
        'bg-[#1f5d2b]',
        'bg-red-500',
        'bg-gradient-to-r',
        'bg-gradient-to-l',
        'bg-gradient-to-t',
        'bg-gradient-to-b',
        'bg-gradient-to-tr',
        'bg-gradient-to-bl',
        'from-[#1f5d2b]',
        'to-[#a2b917]',
        'from-[#a2b917]',
        'to-[#1f5d2b]',
        'hover:border-[#1f5d2b]',
        'border-[#a2b917]',
        'text-red-500',
        'text-gray-500',
        '!text-white',
        'md:gap-6',
        'opacity-50',
        'backdrop-blur-sm',
        'cursor-zoom-in',
        'sm:grid-cols-2',
        'backdrop-blur-md',
        'hover:bg-[#a2b917]',
        'text-[#1f5d2b]',
        'hover:text-[#1f5d2b]',
        // Typography
        'text-[0.7rem]',
        'text-sm',
        'text-base',
        'md:text-base',
        'md:text-lg',
        'lg:text-xl',
        'md:text-2xl',
        'sm:text-xl',
        'sm:text-2xl',
        'lg:text-3xl',
        '!text-sm',
        '!leading-none',
        '!leading-tight',
        'md:leading-1',
        'md:!leading-2',
        'md:!leading-3',
        'md:!leading-4',
        'md:!leading-5',
        'md:!leading-6',
        'leading-[0.9rem]',
        'font-thin',
        'font-semibold',
        'font-bold',
        'md:font-extrabold',
        '!font-spartan',
        '!font-dancing',
        '!font-lato',
        '!font-montserrat',
        '!font-sans',
        '!whitespace-nowrap',
        'tracking-tight',
        'tracking-wide',
        'uppercase',
        'lowercase',
        'italic',
        // Borders & Rounding
        'border',
        'border-[#a2b917]',
        'hover:border-[#1f5d2b]',
        'rounded-sm',
        'rounded-md',
        'rounded-t',
        'sm:rounded-l',
        'rounded-lg',
        'rounded-2xl',
        'drop-shadow-md',
        'shadow',
        'shadow-md',
        'shadow-lg',
        'shadow-[#1f5d2b]/40',
        'no-underline',
        // Transforms & Transitions
        'scale-75',
        'hover:bg-transparent',
        'md:scale-100',
        'hover:shadow',
        'hover:scale-105',
        'transition',
        'hover:text-[#ffffff]',
        'duration-100',
        'duration-200',
        'duration-300',
        'duration-400',
        'duration-500',
        'duration-600',
        'duration-700',
        'duration-800',
        'duration-900',
        'ease-in-out',
        'hover:text-gray-100',
        'bg-[#ffffff]',
        'h-10',
        'sm:h-16',
        'lg:h-24',
        'text-[#000000]',
        'transform',
        'hover:rotate-1',
        'ease-out',
        'ease-in',
        'ease-in-out',
        // Special & Utility
        'z-[999]',
        'z-[99]',
        'z-[10]',
        'cursor-pointer',
        'max-h-[50vh]',
        'max-h-full',
        'max-h-[50%]',
        'select-none',
        'space-y-4',
        'md:space-y-12',
        'flex-col-reverse',
        'flex-row-reverse',
        'flex-row',
        'md:w-[4rem]',
        'group-hover:block',
        'group-hover:right-0',
        'right-[-10rem]',
        'group',
        'max-h-[5.375rem]',
        'right-[-4rem]',
        'aspect-[5040/1692]',
        'aspect-[16/9]',
        'hover:opacity-100',
        'opacity-60',
        'aspect-4/3',
        'aspect-3/2',
        'aspect-16/9',
        'md:space-y-10',
        'overflow-hidden',
        'overflow-x-auto',
        'overflow-y-scroll',
        'm-4',
        'object-cover',
        'object-center',
        'text-center',
        'text-left',
        'text-right',
        'hover:scale-x-110',
        'focus:scale-x-110',
        'active:scale-x-110',
        'bg-white/50',
        'pl-4',
        'from-white',
        'py-1',
        'top-2',
        'top-3',
        'w-[300px]',
        'h-[300px]',
        'shadow-inner',
        'drop-shadow-md',
        '!text-xs',
        // Arbitrary Variants & Child Styling
        '[&>li]:flex',
        '[&>figure>img]:md:w-full',
        '[&>g-recaptcha]:flex',
        '[&>g-recaptcha]:items-center',
        '[&>g-recaptcha]:justify-center',
        '[&>figure>img]:w-[5rem]',
        '[&>li]:flex-wrap',
        '[&>li]:whitespace-nowrap',
        '[&>li>span]:mr-1',
        '[&>li>a]:!text-white',
        '[&>li>a:hover]:!text-[#a2b917]',
        '[&>p]:text-gray-600',
        '[&>img]:rounded-lg',
        '[&>div>ul>li]:text-[11.2px]',
        // Design system interaction classes used by JS
        'cbc-is-scrolled',
        'is-visible',
        // Pattern for Gradient Detection
        { pattern: /bg-gradient-to-(r|l|t|b|tr|tl|br|bl)/ },
    ],
    theme: {
        extend: {
            colors: Object.assign({}, extendedColors, {
                'biotech-primary': '#2e7d32',
                'biotech-dark': '#1b5e20',
                'biotech-light': '#4caf50',
                'biotech-accent': '#76ff03',
                'biotech-dark-bg': '#212121',
                'biotech-slate': '#64748b'
            }),
            spacing: {
                'shell-x-sm': '1rem',
                'shell-x-md': '1.5rem',
                'shell-x-lg': '3rem',
                'shell-x-xl': '5rem',
                'section-y-sm': '3.5rem',
                'section-y-lg': '5rem'
            },
            borderRadius: {
                xl: 'calc(var(--radius) + 4px)',
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
                xs: 'calc(var(--radius) - 6px)'
            },
            boxShadow: {
                xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
                card: '0 10px 24px rgba(0, 0, 0, 0.10)',
                cardHover: '0 18px 40px rgba(0, 0, 0, 0.16)',
                glow: '0 0 20px rgba(118, 255, 3, 0.3)'
            },
            keyframes: {
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' }
                },
                'fade-in': {
                    from: { opacity: '0' },
                    to: { opacity: '1' }
                },
                'slide-up': {
                    from: { opacity: '0', transform: 'translateY(20px)' },
                    to: { opacity: '1', transform: 'translateY(0)' }
                }
            },
            animation: {
                shimmer: 'shimmer 1.5s linear infinite',
                'fade-in': 'fade-in 0.5s ease-out forwards',
                'slide-up': 'slide-up 0.6s ease-out forwards'
            },
            fontFamily: {
                dancing: ['"Dancing Script"', 'cursive'],
                lato: ['Lato', 'sans-serif'],
                spartan: ['"League Spartan"', 'sans-serif'],
                montserrat: ['Montserrat', 'sans-serif'],
                sans: custom.fontFamily ? custom.fontFamily.split(',').map(s => s.trim()) : ['Inter', 'system-ui', 'sans-serif']
            }
        }
    },
    plugins: []
};
